{% set name = "django-fsm" %}
{% set version = "2.8.0" %}
{% set sha256 = "4649167bf5bd4b2990dd682644d71b52650f120005a98755cfffc1a047a555d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8

about:
  home: http://github.com/kmmbvnr/django-fsm
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Django friendly finite state machine support
  description: django-fsm adds simple declarative states management for django models.
  doc_url: http://github.com/kmmbvnr/django-fsm
  dev_url: http://github.com/kmmbvnr/django-fsm

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
