{% set name = "django-fsm" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-fsm-{{ version }}.tar.gz
  sha256: 0112bcac573ad14051cf8ebe73bf296b6d5409f093e5f1677eb16e2196e263b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.11
    - django >=1.6

test:
  imports:
    - django_fsm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/kmmbvnr/django-fsm
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Django friendly finite state machine support'
  description: django-fsm adds simple declarative states management for django models.
  doc_url: http://github.com/kmmbvnr/django-fsm
  dev_url: http://github.com/kmmbvnr/django-fsm

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
